shared void run() {
    wholeInstantiationEqualityTests();
    wholeFormatTests();
    wholeParseTests();
    wholeStringTests();
    wholePlusTests();
    wholeMinusTests();
    wholeTimesTests();
    wholeDividedTests();
    wholeRemainderTests();
    wholeModTests();
    wholePowerTests();
    wholeComparisonTests();
    wholePredicatesTests();
    wholeHashTests();
    wholeSuccessorTests();
    wholeConversionTests();
    wholeMiscTests();
    print("Whole tests complete");

    testExp();
    testExpm1();
    testLog();
    testLog1p();
    testLog10();
    testSin();
    testSinh();
    testCosh();
    testTanh();
    testCos();
    testTan();
    testAsin();
    testAcos();
    testAtan();
    testAtan2();
    testHypot();
    testSqrt();
    testCbrt();
    testRandom();
    testFloor();
    testCeiling();
    testHalfEven();
    testSumProduct();
    testScalb();
    testRemainder();
    floatTests();
    print("Float tests complete");
}
